info:
  app:
    name: '@project.name@'
    version: '@project.version@'
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
news:
  jwt:
    expiration: 1800000
    secret: ${NEWS_JWT_SECRET}
serv: ''
spring:
  datasource:
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${NEWS_DATABASE_PASSWORD}
    testWhileIdle: true
    url: ${NEWS_DATABASE_URL}
    username: ${NEWS_DATABASE_USERNAME}
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

server.port: ${PORT}